version: "3.4"
x-logging:
  &default-logging
  options:
    max-size: "2m"
    max-file: "5"

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - SERVICES=1
      - NETWORKS=1
      - TASKS=1
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false
    networks:
      - traefik
    logging: *default-logging

  traefik:
    image: traefik
    environment:
      AUTH_USER:
      AUTH_PASSWORD:
      ACME_ENABLE:
      ACME_EMAIL:
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080"
    command:
      - --acme=${ACME_ENABLE}
      - --acme.email=${ACME_EMAIL}
      - --acme.storage=acme.json
      - --acme.onhostrule=${ACME_ENABLE}
      - --acme.entrypoint=https
      - --acme.httpchallenge
      - --acme.httpchallenge.entrypoint=http
    labels:
      traefik.frontend.rule: PathPrefix:/tdash;PathPrefixStrip:/tdash
      traefik.frontend.priority: 100
      traefik.port: 8080
      traefik.frontend.auth.basic.users: ${AUTH_USER}:${AUTH_PASSWORD}
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - /var/log/traefik/:/var/log/traefik/
    depends_on:
      - docker-socket-proxy
    networks:
      - traefik
      - traefik-apps
    logging: *default-logging

networks:
  traefik:
  traefik-apps:
