version: "3.4"
x-logging:
  &default-logging
  options:
    max-size: "2m"
    max-file: "5"

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - SERVICES=1
      - NETWORKS=1
      - TASKS=1
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false
    networks:
      - traefik
    logging: *default-logging

  traefik:
    image: traefik
    environment:
      AUTH_USER:
      AUTH_PASSWORD:
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080"
    labels:
      traefik.frontend.rule: PathPrefixStrip:/tdash
      traefik.port: 8080
      traefik.frontend.auth.basic: ${AUTH_USER}:${AUTH_PASSWORD}
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - /var/log/traefik/access.log:/var/log/traefik/access.log
    depends_on:
      - docker-socket-proxy
    networks:
      - traefik
      - traefik-apps
    logging: *default-logging

networks:
  traefik:
  traefik-apps:
