---
- name: Copy docker-compose files
  copy:
    src: ../../../../docker
    dest: /home/ubuntu/
    directory_mode: yes
    owner: ubuntu
    group: ubuntu

- name: Adjust permissions
  file:
    path: /home/ubuntu/docker
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
    mode: u=rwX,g=rwX,o=rX

- name: Adjust acme.json permission
  file:
    path: /home/ubuntu/docker/proxy/acme.json
    mode: 0600

- name: Copy logrotate config
  copy:
    src: ../files/traefik
    dest: /etc/logrotate.d/
